const fs = require('node:fs');
const path = require('node:path');

const rootDir = __dirname;
const srcDir = path.join(rootDir, 'src');
const pureDir = path.join(srcDir, 'pure');
const distDir = path.join(rootDir, 'dist');
const distFile = path.join(distDir, 'Code.gs');

function readSorted(dir, predicate) {
  return fs.readdirSync(dir)
    .filter(predicate)
    .sort()
    .map((name) => ({
      name,
      fullPath: path.join(dir, name),
      contents: fs.readFileSync(path.join(dir, name), 'utf8').trim()
    }));
}

fs.mkdirSync(distDir, { recursive: true });

const pureFiles = readSorted(pureDir, (name) => name.endsWith('.js'));
const appFiles = readSorted(srcDir, (name) => name.endsWith('.js') && name !== 'appsscript.json');

const banner = [
  '// Generated by appsscript/build.js',
  '// Do not edit dist/Code.gs directly; edit files in src/ instead.',
  ''
].join('\n');

const body = pureFiles.concat(appFiles)
  .map((file) => '// ---- ' + file.name + ' ----\n' + file.contents)
  .join('\n\n');

fs.writeFileSync(distFile, banner + body + '\n', 'utf8');
console.log('Wrote ' + distFile);
